export const MOVIES = [
  {
    id: 'abc123',
    rating: 7.8,
    title: 'The Lost Treasure',
    description:
      "A group of explorers embarks on a journey to find a lost treasure hidden deep in the Amazon rainforest. Along the way, they face numerous challenges and dangers, including wild animals and treacherous terrain. Will they be able to find the treasure before it's too late?",
    year: 2015,
    image: require('../assets/movie-covers/1.png'),
    video: require('../assets/videos/1.mp4'),
    category: 'Action',
  },
  {
    id: 'def456',
    rating: 6.5,
    title: 'Midnight Masquerade',
    description:
      "A young woman attends a masquerade ball and falls in love with a mysterious stranger. As they dance the night away, she wonders who he really is and what secrets he's hiding. Will she be able to uncover the truth and find true love?",
    year: 2018,
    image: require('../assets/movie-covers/2.png'),
    video: require('../assets/videos/2.mp4'),
    category: 'Drama',
  },
  {
    id: '5jKz5P',
    rating: 7.8,
    title: 'Rising Storm',
    description:
      'When a devastating hurricane hits the Florida coast, a group of strangers must come together to survive the storm. As tensions rise and secrets are revealed, they discover that sometimes the biggest threat comes from within.',
    year: 2021,
    image: require('../assets/movie-covers/3.png'),
    video: require('../assets/videos/3.mp4'),
    category: 'Horror',
  },
  {
    id: '1sGh7F',
    rating: 6.5,
    title: 'The Last Laugh',
    description:
      "A struggling stand-up comedian gets a second chance at fame when he is invited to perform on a popular late-night talk show. But when his old rival shows up to steal the spotlight, he must decide if he's willing to go all in for his shot at stardom.",
    year: 2020,
    image: require('../assets/movie-covers/4.png'),
    video: require('../assets/videos/4.mp4'),
    category: 'Drama',
  },
  {
    id: '3bNf4R',
    rating: 8.2,
    title: 'Paradise Island',
    description:
      'When a group of friends take a vacation to a secluded island paradise, they soon discover that things are not as they seem. As they uncover the dark secrets of the island, they must fight to survive and escape the deadly paradise.',
    year: 2019,
    image: require('../assets/movie-covers/5.png'),
    video: require('../assets/videos/5.mp4'),
    category: 'Comedy',
  },
  {
    id: '7zTb2H',
    rating: 5.9,
    title: 'Deserted Highway',
    description:
      'A group of travelers are stranded on a deserted highway when their car breaks down. As they try to find help, they soon realize that they are not alone on the road. With danger lurking around every turn, they must fight to stay alive and make it to safety.',
    year: 2018,
    image: require('../assets/movie-covers/6.png'),
    video: require('../assets/videos/6.mp4'),
    category: 'Horror',
  },
  {
    id: '9cHd6J',
    rating: 7.1,
    title: 'The Last Stand',
    description:
      'When a group of survivors are forced to make a last stand against a horde of zombies, they must rely on their wits and their weapons to stay alive. As the stakes get higher and the odds get longer, they must come together to fight.',
    year: 2017,
    image: require('../assets/movie-covers/7.png'),
    video: require('../assets/videos/7.mp4'),
    category: 'Action',
  },
  {
    id: '6tLg9M',
    rating: 6.8,
    title: 'Midnight Express',
    description:
      'A young man is caught smuggling toy bears out of Turkey and sentenced to life in a brutal toy store. As he fights to survive the harsh conditions and brutal treatment, he must also find a way to escape and reclaim his freedom.',
    year: 2016,
    image: require('../assets/movie-covers/8.png'),
    video: require('../assets/videos/8.mp4'),
    category: 'Horror',
  },
  {
    id: 'd08f9c',
    rating: 8.2,
    title: 'The Hidden Gem',
    description:
      'A group of adventurers embarks on a perilous journey to find a legendary gem that is said to possess incredible power. As they traverse treacherous landscapes and face many obstacles, they discover that the true value of the gem lies.',
    year: 2019,
    image: require('../assets/movie-covers/9.png'),
    video: require('../assets/videos/9.mp4'),
    category: 'Action',
  },
  {
    id: 'b6a7f5',
    rating: 7.9,
    title: 'Echoes in the Wind',
    description:
      "A young woman returns to her hometown to confront the ghosts of her past and unravel the mystery surrounding her father's death. Along the way, she reconnects with old friends and discovers a renewed sense of purpose and belonging.",
    year: 2020,
    image: require('../assets/movie-covers/10.png'),
    video: require('../assets/videos/10.mp4'),
    category: 'Horror',
  },
  {
    id: 'e3d2b9',
    rating: 6.5,
    title: 'The Last Expedition',
    description:
      'A team of explorers sets out on a dangerous mission to reach the summit of an uncharted mountain in the heart of the Amazon. As they push themselves to their limits and face unforeseen challenges, they realize that the true goal.',
    year: 2018,
    image: require('../assets/movie-covers/11.png'),
    video: require('../assets/videos/11.mp4'),
    category: 'Drama',
  },
  {
    id: 'f4c9a1',
    rating: 9.1,
    title: 'Art of Survival',
    description:
      'In a post-apocalyptic world where society has crumbled and resources are scarce, a lone survivor must use all of her skills and knowledge to stay alive and find a way to rebuild. Along the way, she meets a group of like-minded individuals.',
    year: 2017,
    image: require('../assets/movie-covers/12.png'),
    video: require('../assets/videos/12.mp4'),
    category: 'Comedy',
  },
  {
    id: 'a1b2c3',
    rating: 8.0,
    title: 'The Lost City',
    description:
      'An archaeologist discovers an ancient city hidden deep in the jungle, and must navigate treacherous terrain and outsmart rival treasure hunters to uncover its secrets. Along the way, he forms a bond with a local guide and gains a newfound perspective.',
    year: 2016,
    image: require('../assets/movie-covers/13.png'),
    video: require('../assets/videos/13.mp4'),
    category: 'Action',
  },
  {
    id: 'c2b4d9',
    rating: 7.3,
    title: 'The Road Less Traveled',
    description:
      'A disillusioned businessman leaves his corporate job and embarks on a journey of self-discovery, traveling across the country and encountering a variety of people and experiences along the way. Through his adventures, he learns to appreciate the simple things in life and find happiness in unexpected places.',
    year: 2015,
    image: require('../assets/movie-covers/14.png'),
    video: require('../assets/videos/14.mp4'),
    category: 'Drama',
  },
  {
    id: 'cf7ba8',
    rating: 7.5,
    title: 'Crimson Solitude',
    description:
      'A retired detective is pulled back into the world of crime when a serial killer starts targeting his old colleagues. As he investigates the case, he discovers a dark conspiracy that threatens to destroy the entire police force.',
    year: 2018,
    image: require('../assets/movie-covers/15.png'),
    video: require('../assets/videos/15.mp4'),
    category: 'Drama',
  },
  {
    id: 'a0f67e',
    rating: 9.2,
    title: 'Neon Horizon',
    description:
      'In a future where the world is ruled by corporations, a group of hackers must band together to bring down the system and restore freedom to the people. But as they get closer to their goal, they realize that not everything is as it seems.',
    year: 2021,
    image: require('../assets/movie-covers/16.png'),
    video: require('../assets/videos/16.mp4'),
    category: 'Drama',
  },
  {
    id: 'e8c42b',
    rating: 8.1,
    title: 'Midnight Symphony',
    description:
      "A talented musician is forced to confront his past when he is invited to perform at a concert honoring his late mentor. As he rehearses for the show, he begins to uncover the truth behind his mentor's mysterious death.",
    year: 2019,
    image: require('../assets/movie-covers/17.png'),
    video: require('../assets/videos/17.mp4'),
    category: 'Drama',
  },
  {
    id: 'f9a73c',
    rating: 5.3,
    title: 'Electric Dreams',
    description:
      'In a world where people can upload their consciousness into a virtual reality, a man must navigate a dangerous game to save his girlfriend from being trapped in the system forever.',
    year: 2020,
    image: require('../assets/movie-covers/18.png'),
    video: require('../assets/videos/18.mp4'),
    category: 'Comedy',
  },
  {
    id: 'b6d19e',
    rating: 7.9,
    title: 'Last Resort',
    description:
      'A group of strangers find themselves stranded on a deserted island with no way off. As they work together to survive, they begin to uncover the dark secrets that led to their predicament.',
    year: 2015,
    image: require('../assets/movie-covers/19.png'),
    video: require('../assets/videos/19.mp4'),
    category: 'Horror',
  },
  {
    id: 'c2f84d',
    rating: 6.5,
    title: 'Broken Visions',
    description:
      'A young artist begins to experience vivid and terrifying visions that threaten to consume her. As she tries to unravel the mystery behind her visions, she discovers a dark and twisted conspiracy that has been hidden for years.',
    year: 2018,
    image: require('../assets/movie-covers/20.png'),
    video: require('../assets/videos/20.mp4'),
    category: 'Action',
  },
];
