export const SCREENS = {
  DISCOVER: 'DISCOVER_SCREEN',
  MOVIE_DETAIL: 'MOVIE_DETAIL_SCREEN',
  WATCHLIST: 'WATCHLIST_SCREEN',
};

export const NAVIGATORS = {
  DISCOVER: 'DISCOVER_NAVIGATOR',
  MOVIE_DETAIL: 'MOVIE_DETAIL_NAVIGATOR',
  WATCHLIST: 'WATCHLIST_NAVIGATOR',
};
